#!/bin/bash

WALLPAPER_DIR="$HOME/.dotfiles/wallpapers"
INDEX_FILE="$HOME/.cache/.wallpaper_index"

mapfile -t WALLPAPERS < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" \) | sort)

TOTAL=${#WALLPAPERS[@]}

if [[ ! -f $INDEX_FILE ]]; then
    echo 0 > "$INDEX_FILE"
fi

INDEX=$(<"$INDEX_FILE")
feh --bg-scale "${WALLPAPERS[$INDEX]}"
INDEX=$(( (INDEX + 1) % TOTAL ))
echo $INDEX > "$INDEX_FILE"
