font_size 16
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# hide_window_decorations yes
bold_font auto
bold_color bright
allow_remote_control yes
term xterm-kitty

scrollback_lines 2000
enable_smooth_scrolling yes

tab_bar_edge bottom
tab_bar_style powerline
tab_title_template "{index}"   

include Night3024.conf
